"""
Utilities for loading L2 normalization coefficients.

This module provides functions to load the polynomial coefficients (a, b, c)
for L2 normalization from threshold files generated by estimate_l2_norm.py.
"""
import numpy as np
import os


def load_l2_coeffs(dataset_name='lfw', checkpoint_dir='face_recognition/checkpoints'):
    """
    Load L2 normalization coefficients for a specific dataset.

    Args:
        dataset_name (str): Dataset name (lfw, cfp_fp, cplfw, agedb_30, calfw)
        checkpoint_dir (str): Directory containing threshold files

    Returns:
        tuple: (a, b, c) polynomial coefficients

    Raises:
        FileNotFoundError: If threshold file doesn't exist
        ValueError: If file format is invalid

    Example:
        >>> a, b, c = load_l2_coeffs('lfw')
        >>> model = CryptoFaceNet4(l2_norm_coeffs=(a, b, c))
    """
    # Map dataset names to threshold file names
    dataset_map = {
        'lfw': 'threshold_lfw.txt',
        'cfp_fp': 'threshold_cfp_fp.txt',
        'cplfw': 'threshold_cplfw.txt',
        'agedb_30': 'threshold_agedb_30.txt',
        'calfw': 'threshold_calfw.txt',
    }

    if dataset_name not in dataset_map:
        raise ValueError(
            f"Unknown dataset: {dataset_name}. "
            f"Valid datasets: {list(dataset_map.keys())}"
        )

    threshold_file = os.path.join(checkpoint_dir, dataset_map[dataset_name])

    if not os.path.exists(threshold_file):
        raise FileNotFoundError(
            f"Threshold file not found: {threshold_file}\n"
            f"Please run face_recognition/utils/estimate_l2_norm.py first."
        )

    # Read and parse coefficients
    # Format: x3, x1, x2, a, b, c, threshold (one line per fold)
    coeffs = []
    with open(threshold_file, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            parts = line.split(',')
            if len(parts) >= 7:
                a_val = float(parts[3])
                b_val = float(parts[4])
                c_val = float(parts[5])
                coeffs.append((a_val, b_val, c_val))

    if not coeffs:
        raise ValueError(f"No valid coefficients found in {threshold_file}")

    # Average across folds
    a = np.mean([c[0] for c in coeffs])
    b = np.mean([c[1] for c in coeffs])
    c = np.mean([c[2] for c in coeffs])

    return a, b, c


def get_default_coeffs():
    """
    Get default L2 normalization coefficients.

    Returns LFW coefficients as default.

    Returns:
        tuple: (a, b, c) polynomial coefficients
    """
    try:
        return load_l2_coeffs('lfw')
    except (FileNotFoundError, ValueError):
        # Fallback to hardcoded defaults
        # These are approximate values from LFW dataset
        return 2.41e-07, -2.44e-04, 1.09e-01


def print_all_coeffs(checkpoint_dir='face_recognition/checkpoints'):
    """
    Print L2 normalization coefficients for all datasets.

    Args:
        checkpoint_dir (str): Directory containing threshold files
    """
    datasets = ['lfw', 'cfp_fp', 'cplfw', 'agedb_30', 'calfw']

    print("="*70)
    print("L2 Normalization Coefficients")
    print("="*70)

    for dataset in datasets:
        try:
            a, b, c = load_l2_coeffs(dataset, checkpoint_dir)
            print(f"{dataset:10s}  a={a:.6e}, b={b:.6e}, c={c:.6e}")
        except (FileNotFoundError, ValueError) as e:
            print(f"{dataset:10s}  Error: {e}")

    print("="*70)


if __name__ == "__main__":
    # Print coefficients for all datasets
    print_all_coeffs()
